### ISSUE TITLE
建议修改docker compose配置

### ISSUE THREAD

**Issue by linjiananallnt** [StarCrossPortal/swallow#3]
不是简单的使用路由模式 host，而是通过映射端口的方式带出。其中数据库不建立网卡，仅通过容器进行通信。

```
version: "3.2"
services:
  swallow:
    image: daxia/swallow:latest
    container_name: swallow_web
    network_mode: "bridge"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    ports:
      - "18000:1890"
    volumes:
      - type: bind
        source: "./"
        target: "/root/code"
  mysql:
    image: daxia/swallow:mysql57
    container_name: swallow_mysql
    network_mode: "container:swallow_web"
    environment:
      - MYSQL_ROOT_PASSWORD=dolphin123!
      - TZ=Asia/Shanghai
    restart: always
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
```
